create table building_dong (
  pnu varchar(19),
  building_pk varchar(33),
  register_type varchar(2),
  address varchar,
  road_address varchar,
  building_name varchar,
  dong_name varchar,
  main_sub_type varchar,
  site_area numeric,
  bc_area numeric,
  bc_ratio numeric,
  gf_area numeric,
  far_gf_area numeric,
  fa_ratio numeric,
  structure_code varchar(2),
  structure_name varchar,
  structure_detail varchar,
  use_code varchar(5),
  use_name varchar,
  use_detail varchar,
  sedae_count numeric,
  gagu_count numeric,
  ho_count numeric,
  height numeric,
  floor_count numeric,
  under_floor_count numeric,
  permit_date varchar(8),
  construction_date varchar(8),
  approval_date varchar(8),
  created_date varchar(8),
  uploaded_at timestamp default current_timestamp
);
create index index_building_dong_on_pnu on building_dong (pnu);
